#version: "3.9"  # optional but good to have

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: user_platform_db
      MYSQL_USER: berlin
      MYSQL_PASSWORD: berlin@123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # <-- Persistent MySQL data storage
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: 1
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: berlin
      DB_PASSWORD: berlin@123
      DB_NAME: user_platform_db
      DJANGO_SECRET_KEY: "django-insecure-4j-q2^gpu9&%imydt@@vq*h0i#9#(yv0)&q5ewvaftj(eocs2="
    command: >
      sh -c "
        python wait_for_db.py &&
        python manage.py migrate &&
        gunicorn auth_project.wsgi:application --workers=3 --threads=2 --timeout=120 --bind 0.0.0.0:8000
      "

  nginx:
      image: ankushp1650/zerorisktrader-nginx:latest
      ports:
        - "80:80"
      depends_on:
        - web
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
