# Generated by Django 5.0.7 on 2024-10-28 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2000-01-01')),
                ('stock_name', models.CharField(max_length=100, null=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Final_holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('investment_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockJason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refresh_data', models.DateField(default='2000-01-01')),
                ('stock_name', models.CharField(max_length=100)),
                ('meta_data', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='available_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='invested_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='currentprice',
            index=models.Index(fields=['date'], name='date_index'),
        ),
        migrations.AddConstraint(
            model_name='currentprice',
            constraint=models.UniqueConstraint(fields=('user', 'stock_name', 'date', 'close'), name='unique_stock_currentprice'),
        ),
        migrations.AddConstraint(
            model_name='final_holding',
            constraint=models.UniqueConstraint(fields=('user', 'stock_symbol'), name='unique_user_stock'),
        ),
        migrations.AddIndex(
            model_name='stockjason',
            index=models.Index(fields=['last_refresh_data'], name='last_refresh_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockjason',
            constraint=models.UniqueConstraint(fields=('user', 'stock_name', 'last_refresh_data'), name='unique_user_stock_mydata'),
        ),
    ]
