# Generated by Django 5.0.7 on 2025-04-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_currentprice_final_holding_stockjason_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_data_fetch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
