# Generated by Django 5.2 on 2025-08-07 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_last_data_fetch_date_usertrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('linear_model_success_rate', models.FloatField()),
                ('linear_model_directional_success_rate', models.FloatField()),
                ('linear_model_avg_error', models.FloatField()),
                ('decision_tree_model_success_rate', models.FloatField()),
                ('decision_tree_model_directional_success_rate', models.FloatField()),
                ('decision_tree_model_avg_error', models.FloatField()),
                ('random_forest_model_success_rate', models.FloatField()),
                ('random_forest_model_directional_success_rate', models.FloatField()),
                ('random_forest_model_avg_error', models.FloatField()),
                ('svm_model_success_rate', models.FloatField()),
                ('svm_model_directional_success_rate', models.FloatField()),
                ('svm_model_avg_error', models.FloatField()),
                ('lstm_model_success_rate', models.FloatField()),
                ('lstm_model_directional_success_rate', models.FloatField()),
                ('lstm_model_avg_error', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('last_refreshed', models.DateField()),
                ('date', models.DateField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('close', models.FloatField()),
                ('linear_model', models.FloatField()),
                ('lstm_model', models.FloatField()),
                ('decision_tree_model', models.FloatField()),
                ('random_forest_model', models.FloatField()),
                ('svm_model', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BestModelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('success_rate', models.FloatField()),
                ('directional_success_rate', models.FloatField()),
                ('average_error', models.FloatField()),
                ('normalized_models_score', models.FloatField()),
                ('best_model', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock_name', 'model_name', 'best_model')},
            },
        ),
        migrations.CreateModel(
            name='LSTMModelStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('model_blob', models.BinaryField()),
                ('scaler_blob', models.BinaryField()),
                ('sequence_length', models.IntegerField(default=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock_name')},
            },
        ),
    ]
