# Generated by Django 5.2 on 2025-07-28 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_bestmodelrecord_stockperformance_stockprediction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bestmodelrecord',
            unique_together={('user', 'stock_name', 'model_name', 'best_model')},
        ),
    ]
