# Generated by Django 5.2 on 2025-09-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_stockperformance_stockprediction_bestmodelrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockperformance',
            name='lstm_model_avg_error',
        ),
        migrations.RemoveField(
            model_name='stockperformance',
            name='lstm_model_directional_success_rate',
        ),
        migrations.RemoveField(
            model_name='stockperformance',
            name='lstm_model_success_rate',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='lstm_model',
        ),
    ]
